[request_definition]
r = sub, obj, act, field

[policy_definition]
p = sub_role, obj_type, act, field, effect

[policy_effect]
e = some(where (p.eft == allow))

[matchers]
m = r.sub == p.sub_role && r.obj == p.obj_type && r.act == p.act && (p.field == "*" || r.field == p.field) && p.effect == "allow"
